apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: test-ingress
  namespace: xom-bff-dev
spec:
  rules:
    - host: '*'
      http:
        paths:
          - path: /test
            backend:
              serviceName: tootest-service
              servicePort: 8080

