# This is a basic workflow to help you get started with Actions

name: TooTest

# Controls when the action will run. 
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
env:
  JAVA_VERSION: '1.8'                # set this to the Java version to use

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build-jar:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: ${{ env.JAVA_VERSION }}
      # Gradle
      - name: Build with Gradle
        run: ./gradlew build bootJar
    
      - name: Build Gradle Success
        run: |
          echo Gradle Success Build Success!
          pwd
          ls
          echo list: build/libs
          cd build/libs
          ls
  Deploy-to-Azure-Web-App:
    needs: [ build-jar ]
    runs-on: ubuntu-latest
    steps:
#       - uses: azure/login@v1
#         with:
#           creds: ${{ secrets.AZURE_CREDENTIALS_TOOTEST }}
#           allow-no-subscriptions: true
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'TooTest'
          slot-name: 'production'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: '${{ github.workspace }}/build/libs/*.jar'

 
