# This is a basic workflow to help you get started with Actions

name: wpctl
 
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Hi, Too
          eval "$(curl -s -L https://raw.githubusercontent.com/toojannarong/tooxx-springboot-gradle-kotlin/main/wpctl-install.sh)"
          echo current dir: $(pwd)
          ls
          echo to wpctl then ls
          cd wpctl && ls
          echo current dir: $(pwd)
          ./wpctl
          
