name: K8S Deploy To Dev
on:
  workflow_dispatch:
    inputs:
    logLevel:
      description: 'Log level'
      required: true
      default: 'warning'
  push:
    branches:
      - main

jobs:
  deploy:
    name: Build And Deploy To Dev
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Login to GitHub Packages Docker Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Generate secret from docker config
        run: |
          BASE64=$(cat $HOME/.docker/config.json | base64 -w 0)
          sed -i "s/BASE64_CREDENTIAL/$BASE64/g" ./kubernetes/pullImageSecret.yml
      - name: Apply YAML to xom-bcs-dev
        uses: Consensys/kubernetes-action@master
        env:
          KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
        with:
          args: apply -R -f kubernetes/pullImageSecret.yml -f kubernetes/namespace.yml -f kubernetes/deploy.yaml -f kubernetes/service.yaml

      - name: Sleep for 60s to let cluster pull image
        uses: jakejarvis/wait-action@master
        with:
          time: '60s'